### ISSUE TITLE
Support for associate method in BelongsTo

### ISSUE THREAD

**Issue by pedrofmj** [topclaudy/compoships#100]
Hi there. I'm using Compoships, and i just could see that method associate is not supported in BelongsTo relationships, because it tries to execute the original associate method, that has no support for multiple columns foreign keys.

I just developed locally in my project (changing inside vendor/awobaz/compoships/src/Database/Relations/BelongsTo.php) the fix for this. Could you please see if you guys could put this inside?

/// ---- TO BE PUT INSIDE vendor/awobaz/compoships/src/Database/Relations/BelongsTo.php
/// remember to put also the reference: use Illuminate\Database\Eloquent\Model;

    /**
     * Associate the model instance to the given parent.
     *
     * @param  \Illuminate\Database\Eloquent\Model|int|string  $model
     * @return \Illuminate\Database\Eloquent\Model
     */
    public function associate($model)
    {
        if (is_array($this->ownerKey)) {

            $ownerKey = $model instanceof Model ? $model->getAttribute($this->ownerKey) : $model;
            for ($i = 0; $i < count($this->foreignKey); $i++) {
                $foreignKey = $this->foreignKey[$i];
                $value = $ownerKey[$i];
                $this->child->setAttribute($foreignKey, $value);
            }

            if ($model instanceof Model) {
                $this->child->setRelation($this->relationName, $model);
            } else {
                $this->child->unsetRelation($this->relationName);
            }

            return $this->child;

        } else {
            return parent::associate($model);
        }
    }

**Comment by pedrofmj** [comment]
I already made a PR for this.

**Comment by topclaudy** [comment]
Released in 2.0.5. Thanks :)
