### ISSUE TITLE
Is the set of local-foreign key pairs being compared with "AND" or "OR"?

### ISSUE THREAD

**Issue by nilecrocodile** [topclaudy/compoships#109]
(Sorry for not reporting the issue, but simply asking, but I think this is a topical question)
For ex.:
Table words:
 - id
 - title
 - title_translation_eng
 - title_translation_de
 - title_translation_fr
 - title_translation_jp

I need for each word to obtain all other words that have the same title in one of the languages.

Can I do this:
```
class Word extends Model
{
    use \Awobaz\Compoships\Compoships;
    
    public function sameWords()
    {
        return $this->hasMany('App\Models\Word', [
            'title_translation_eng',
            'title_translation_de',
            'title_translation_fr',
            'title_translation_jp'
        ], [
            'title_translation_eng',
            'title_translation_de',
            'title_translation_fr',
            'title_translation_jp'
        ]);
    }
}
```

In other words, to find a relationship, must all or any one of the set of foreign-local key pairs match?

**Comment by topclaudy** [comment]
All of foreign-local key pairs must match

**Comment by nilecrocodile** [comment]
Thank you.
