### ISSUE TITLE
PHP 8 compatability?

### ISSUE THREAD

**Issue by Orillian** [topclaudy/compoships#110]
Just wondering if anyone has tried with Laravel 8 on PHP 8?

I keep meaning to give it a run, but...time. I'm hoping to give it a go this weekend on the testbench, but we will see.

Anyways for the two people that haven't seen it.
https://blog.laravel.com/laravel-php-8-support

**Comment by lsalazarm99** [comment]
We use this package in Laravel 8 with PHP 8. It works great!
