### ISSUE TITLE
HasMany relationship are inefficient in v2.1

### ISSUE THREAD

**Issue by lsalazarm99** [topclaudy/compoships#117]
Given this:
```php
class Course extend Model
{
    ...
    public function enrollments(): HasMany
    {
        return $this->hasMany(Enrollment::class, ['course_year', 'course_code'], ['course_year', 'course_code']);
    }
}
```

Before 2.1, assuming I'm requesting the list of users enrolled in the course 2020-A and 2021-B, the generated query for the relationship would be something like this:
```sql
SELECT *
FROM enrollments
WHERE ((course_year = '2020' AND course_code = 'A') AND (course_year = '2021' AND course_code = 'B'))
```

This would return a list of enrollments of 2 courses (the 2020-A and the 2021-B).

Now, in 2.1, the generated query looks like this:
```sql
SELECT *
FROM enrollments
WHERE ((course_year IN ('2020', '2021')) AND (course_code IN ('A', 'B')))
```

This will return a list of enrollments of 4 courses (the 2020-A, 2020-B, 2021-A, and 2021-B). I'm not sure what Compoship does under the hood but, in the end, it only shows the correct list of enrollments. But the problem is the amount of data it returns from the DB.

For example, 15 courses that were dictated in 4 years means PHP will process 60 courses and their relationships (which are many)!

For now, we had to return to 2.0.5.

**Comment by topclaudy** [comment]
It's probably caused by this PR https://github.com/topclaudy/compoships/pull/114. I reverted the changes in 2.1.1. Please try and let me know

**Comment by qwertyuu** [comment]
Maybe add a test case that covers this, to be sure I don't cause this trouble in the future :)

**Comment by topclaudy** [comment]
@qwertyuu Yep! That's a good idea.

**Comment by lsalazarm99** [comment]
I have tried the new version (2.1.1) and it's fixed. Thanks.
