### ISSUE TITLE
Not compatible with eloquent-query-cache

### ISSUE THREAD

**Issue by myckhel** [topclaudy/compoships#119]
When used with [laravel-eloquent-query-cache](https://github.com/renoki-co/laravel-eloquent-query-cache) i got this error:
> Trait method Awobaz\Compoships\Compoships::newBaseQueryBuilder has not been applied as App\User::newBaseQueryBuilder, because of collision with Rennokki\QueryCache\Traits
\QueryCacheable::newBaseQueryBuilder

https://github.com/renoki-co/laravel-eloquent-query-cache/issues/67

**Comment by topclaudy** [comment]
Unfortunately, you'll have to drop one of the conflicting packages.

**Comment by erikn69** [comment]
You can make your own trait mixing the two codes
