### ISSUE TITLE
Use trait on related model makes me use compoships for all models, including vendor models

### ISSUE THREAD

**Issue by mankowitz** [topclaudy/compoships#24]
I have two models that are related using compoships. The problem is that all my models are related to each other, including some models that are vendor-defined. I now have to add the trait to all my models as well as those provided by the vendor (which may be more difficult and prevents easy upgrade).

Is there any way to relax the requirement for both models being compships?

**Comment by topclaudy** [comment]
The requirement is to ensure that eager loading works. Otherwise you'll get the error https://github.com/topclaudy/compoships/issues/1.
