### ISSUE TITLE
Using make() function on relation returns error

### ISSUE THREAD

**Issue by mdemblani** [topclaudy/compoships#25]
Since, there is a possibility of a model having a composite key, there are certain scenarios where we just need the instance of the related model without persisting it to the database. To achivie this, there is a `make()` function in relations such as HasOneOrMany. 

Currently it defaults to the one provided by Eloquent, and hence it returns an error.

**Comment by topclaudy** [comment]
Fixed in 1.1.1. Thanks for the PR :)
