### ISSUE TITLE
has() not working on self relations

### ISSUE THREAD

**Issue by JensMakeable** [topclaudy/compoships#27]
Thank you for a nice package!

I'm having troubles using has() when the relationsship refers to it's own class.

To reproduce:

In your test-suite, add following relation to TrackingTask.php:

    public function subtasks()
    {
        return $this->hasMany(TrackingTask::class, 
            ['booking_id', 'vehicle_id'],
            ['booking_id', 'vehicle_id']);
    }

Try adding and running following unittest:

    public function testHasForSelfRelation()
    {
        $trackingTask = TrackingTask::has('subtasks')->get()->toArray();

        $this->assertInternalType('array', $trackingTask);
    }

It is the method getRelationExistenceQueryForSelfRelation that tries to make a string comparision.

I might have time to take a further look and make a PR, but not today unfortunatly.

**Comment by topclaudy** [comment]
Thanks for this detailed issue. I added a fix. You may test using the master branch and give feedback.

**Comment by JensMakeable** [comment]
Wow, you are fast :-)
It seems to work perfect. Beautiful!

Thank you a lot!

**Comment by topclaudy** [comment]
Fixed in 1.1.2
