### ISSUE TITLE
In-correct if-clause in the code-base

### ISSUE THREAD

**Issue by mdemblani** [topclaudy/compoships#28]
The check relies on the fact whether the foreign key value is a boolean true. This results in the a wrong relation creation, where it has 2 foreign keys but only one binding in it's where clause. 

[https://github.com/topclaudy/compoships/blob/master/src/Database/Eloquent/Relations/BelongsTo.php#L25](https://github.com/topclaudy/compoships/blob/master/src/Database/Eloquent/Relations/BelongsTo.php#L25)

**Comment by topclaudy** [comment]
@mdemblani Thanks for reporting this issue. Can you please provide more details (some code example with the resulting query)?

**Comment by topclaudy** [comment]
About to close this... please reopen if you have more details

**Comment by mdemblani** [comment]
Hi, 

Regarding the issue, consider the following case, there is a relation between 2 models, says
- Model A
- Model B

The models are related as follows: Model B `belongsTo` Model A on two keys : `X` and `Y`, which are both of type `integer`. The foreign key constraints are managed on the application level, and not on the DB(there was a reason to do this). 

The relation foreign keys start as follows: for `X` they start from 1 and for `Y` they start from 0.
The relation had to start with 0, due to the underlying requirements  which results in the following case:

In my final query, just with the foreign keys, I have 2 foreign keys(`X` and `Y`) as defined by my relation but only a single binding (for `X`). The binding for `Y` is not considered, since the check on Line 25 performs a check on whether the value is a boolean true and not whether the value is set or put up a default value of `null`. This results in an error, in the form of a wrong query being generated.

**Comment by topclaudy** [comment]
@mdemblani Thanks for the details. I pushed a fix to the master branch. You may test it and give me feedback.

**Comment by topclaudy** [comment]
Fixed in 1.1.3
