### ISSUE TITLE
trait \Awobaz\Compoships\Compoships

### ISSUE THREAD

**Issue by KoIIIeY** [topclaudy/compoships#3]
After adding 
use \Awobaz\Compoships\Compoships

no relationships works on table. Every (hasOne, hasMany) relation returns null.

`public function postedTests(){
        return $this->hasMany('\App\PostedTest', 'language_id', 'language_id');
        return $this->hasMany('\App\PostedTest', ['language_id', 'participant_user_id'], ['language_id','participant_user_id']);
    }`

While I used trait, every relation returns null, once remove trait - old relations work. 
Laravel 5.4.

**Comment by KoIIIeY** [comment]
ParticipantLanguage :

`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class ParticipantLanguage extends Model
{

    use \Awobaz\Compoships\Compoships;

public function postedTests(){
        return $this->hasMany('\App\PostedTest', ['language_id', 'participant_user_id'], ['language_id','participant_user_id']);
    }`


And postedTest:

`<?php

namespace App;

use App\Upload\Uploadable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class PostedTest extends Model
{
    use Uploadable, \App\Traits\ModelHelper, \Awobaz\Compoships\Compoships
        ;
`

**Comment by topclaudy** [comment]
Your code is correct. Which version of Compoship are you using?

**Comment by KoIIIeY** [comment]
> "name": "awobaz/compoships",
            "version": "1.0.1",
            "source": {
                "type": "git",
                "url": "https://github.com/topclaudy/compoships.git",
                "reference": "364c18858e2f871774f379abbd15c2592d75f2e4"
            },

**Comment by topclaudy** [comment]
Use the last version (1.0.2)

**Comment by KoIIIeY** [comment]
Work, thx.
