### ISSUE TITLE
Not unique table/alias error

### ISSUE THREAD

**Issue by nicholaszuccarelli** [topclaudy/compoships#38]
I'm having an issue with the latest version of Compoships whenever I use whereHas()

The code:
```
        $type = $this->type;

SubType::query()
            ->whereHas('types', function ($query) {
                $query->where('id', '=', config('constants.types.licenceTypes'));
            })
            ->whereIn('id', $type->extra_data['available_licences'])
            ->get($columns);
```

The SQL error I get:

 `"SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'type_has_data' (SQL: select id, name, colour from type_data where exists (select * from types inner join type_has_data on types.`id` = type_has_data.`type_id` inner join type_has_data on types.`id` = type_has_data.`type_id` where type_data.`id` = type_has_data.`data_id` and types.`id` = LICENCE-TYPES and type_data.`id` = type_has_data.`data_id` and types.`id` = LICENCE-TYPES) and id in (BEE_KEEPER_PERMIT, COMMERCIAL_SNAKE_LICENCE, FULL_TECHNICIAN, TIMBER_PEST) and type_data.`deleted_at` is null)"`

```
(SQL:SELECT id, 
       NAME, 
       colour 
FROM   type_data 
WHERE  EXISTS 
       ( 
                  SELECT     * 
                  FROM       types 
                  INNER JOIN type_has_data 
                  ON         types.`id` = type_has_data.`type_id` 
                  INNER JOIN type_has_data 
                  ON         types.`id` = type_has_data.`type_id` 
                  WHERE      type_data.`id` = type_has_data.`data_id` 
                  AND        types.`id` = licence-types 
                  AND        type_data.`id` = type_has_data.`data_id` 
                  AND        types.`id` = licence-types) 
AND    id IN (bee_keeper_permit, 
              commercial_snake_licence, 
              full_technician, 
              timber_pest) 
AND    type_data.`deleted_at` IS NULL)
```

I notice that it is doing the inner join on the table twice, which is the error.
If I remove the Compoships trait from the SubType model then I get no errors and it works properly.

**Comment by topclaudy** [comment]
What's your exact version of Laravel (5.?.?)?

**Comment by nicholaszuccarelli** [comment]
Off the top of my head, we are using the latest available version of 5.7

**Comment by nicholaszuccarelli** [comment]
Checked now. 5.7.22

**Comment by topclaudy** [comment]
Can you try `SubType::whereHas(...)` instead of `SubType::query()->whereHas(...)`? Also consider upgrading to 1.1.6
