### ISSUE TITLE
belongsTo does not work on laravel 5.7

### ISSUE THREAD

**Issue by sinbino** [topclaudy/compoships#39]
Using Array for foreignKey on belongsTo in Laravel 5.7 will cause the following warning when accessing the relation:

PHP Notice: Array to string conversion in /srv/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php on line 78

In Larvel 5.7, the code added to the getResults method of the Illuminate / Database / Eloquent / Relations / BelongsTo class references the foreignKey member variable, which is probably the cause.

**Comment by topclaudy** [comment]
What is your version of Laravel (5.7.?) and Compoships?

**Comment by sinbino** [comment]
I apologize for the lack of my information.

laravel/framework v5.7.21
awobaz/compoships 1.1.5

Apparently, it seems that what was added with the latest update of laravel/framework is causing problems.
https://github.com/laravel/framework/commit/1103e1d28d77b8adf29e26af9b7b9e3af064e559

**Comment by topclaudy** [comment]
Fixed in 1.1.6. Please upgrade Compoships.

**Comment by sinbino** [comment]
thankyou!
