### ISSUE TITLE
Dependencies' versions locked in composer.lock

### ISSUE THREAD

**Issue by V-Srv** [topclaudy/compoships#42]
You have `composer.lock` file in your package. So when I added `compoships` into my project it downgraded some of my dependencies. 
This could lead to some major incompatibility in the future.
I do not think that the package needs this file, `composer.json` is enough.
Do you think you could remove `composer.lock`?

**Comment by topclaudy** [comment]
It's to ensure that contributors use the same versions of dependencies.

**Comment by V-Srv** [comment]
Thank you for your answer. I still think additional package should not downgrade the whole project.
You could close this issue.

**Comment by topclaudy** [comment]
Composer doesn't downgrade dependencies when adding new package. You might have an issue with your setup.

**Comment by V-Srv** [comment]
Let's say I have `awesome/package: ^1.0` in my projects' `composer.json`. The version I am using is locked on 1.2 in `composer.lock`.
And then I apply some package with `awesome/package: 1.1` in `composer.lock`.
What version do you think will be used in a result? It will be downgraded to `1.1`.

**Comment by topclaudy** [comment]
@V-Srv  The composer.lock is removed in 1.1.8.
