### ISSUE TITLE
Overhead during every query.

### ISSUE THREAD

**Issue by cegprakash** [topclaudy/compoships#44]
The drawback I face with this library is that it enforces the base model, the derived model and every model which a re connected with these models recursively. In my case every class has to be changed to derive from this Awobaz model instead of Eloquent model (or every model has to use the Compoships trait) which will add an extra overhead to every query. If this can be avoided then this would be good.

I have a very huge project and I had to change every model because of this.

If I don't do that, I get this error.

The related model 'App\\Model\\XYZ' must either extend 'Awobaz\\Compoships\\Database\\Eloquent\\Model' or use the 'Awobaz\\Compoships\\Compoships' trait"

Now my Pull request will not be approved as this will be an overhead to every query. I want to touch maximum 1 file and get this done.

**Comment by topclaudy** [comment]
Can you please give more details about you setup and models (base model, derived models, related models etc.)?

**Comment by cegprakash** [comment]
class A extends Model
{
     protected $guarded = [];
    
   public function myRequiredRelation()
   {      
        return $this::hasMany('App\Model\K', ['b_id', 'c_id'], ['b_id', 'c_id']);        
   }
       
    public function someOtherRelation()
    {
        return $this->belongsTo('App\Model\G');
    }

    public function anotherRelation()
    {
        return $this->hasOne('App\Model\P', 'id', 'p_id');
    }
}

I'm fine with extending  A from Awobaz model. But the library forces me to extend models K, G, P  (also must extend the relationships in G and P because they are now extended from Awobaz too and goes on recursively)

**Comment by topclaudy** [comment]
@cegprakash Good point! This is fixed in 1.1.9.

**Comment by eaverdeja** [comment]
Thank you @topclaudy ! This was a pain point with the package and now it's fixed :+1:

**Comment by cegprakash** [comment]
Is the README still true?

Note: To define a multi-columns relationship from a model A to another model B, both models must either extend Awobaz\Compoships\Database\Eloquent\Model or use the Awobaz\Compoships\Compoships trait

**Comment by cegprakash** [comment]
So I've to touch 2 files.. Not bad..
