### ISSUE TITLE
hasMany relationship doesn't seem to work

### ISSUE THREAD

**Issue by 5chulzi** [topclaudy/compoships#46]
I have the following database structure:

- a user table (id, name, email, ...)
- a conversation table (id, user_id_1, user_id_2)

To get all conversations of a user, I needed to create a relationship on both columns (user_id_{1, 2}) of the conversation table. Therefore I'm using this package. But it doesn't seem to work for me. I'm using the latest version (1.1.9). The following is a code snippet of the relationship in the user model:

`
public function conversations() {
        return $this->hasMany('App\Conversation', ['user_id_1', 'user_id_2']);
    }
`

The conversation model inherits from the compoship eloquent model, the user model uses the trait variant, because it inherits from _Authenticatable_. I'm assuming that the hasMany relation defaults the local keys to **_id_**, but I already tried passing `['id', 'id']` as local keys and it doesn't work either.

EDIT: I should say that I don't get any error. When I call `$user->conversations`, it returns an empty collection. As soon as I pass in only one foreign key (e.g. user_id_1) it works, but obviously gives me the conversations, where the _user_id_1_ equals `$user->id` and not where _user_id_2_ equals `$user->id`, too.

**Comment by topclaudy** [comment]
@5chulzi What you're trying to define is a relationship where `conversation.user_id_1=user.id OR conversation.user_id_2=user.id`. This kind of relationship is not possible with Compoships. If the relationship was defined correctly, Compoships would assume `conversation.user_id_1=user.id AND conversation.user_id_2=user.id` which will always return an empty collection in your scenario, unless users can send messages to themselves.

**Comment by 5chulzi** [comment]
Oh well, then I misunderstood the way Compoships works. Thanks for the clarification. I’ll then have to go for an alternative solution.

**Comment by RaiserWeb** [comment]
@5chulzi your requirement is the same as mine - did you find a solution?

**Comment by 5chulzi** [comment]
At the moment I'm just returning a simple query like this:
```
public function conversations() {
    return Conversation::query()->where('user_id_1', $this->id)->orWhere('user_id_2', $this->id);
}
```

But everytime you need conversations of the user you need call `get()` additionally to really get the results instead of just the query, which is not perfect but enough to be accepted for me.

**Comment by Usama100** [comment]
> Oh well, then I misunderstood the way Compoships works. Thanks for the clarification. I’ll then have to go for an alternative solution.

Did you find any alternate solution? Because I am also facing the same problem as you were facing in this issue. I am getting empty collection also
