### ISSUE TITLE
Doc update request in regard to multi connections

### ISSUE THREAD

**Issue by wojo1206** [topclaudy/compoships#47]
If your models happen to use different connection you must provide `protected $connection = 'connection_name'` for each model. Otherwise, `belongsTo()` will call default database which is defined in `$this` model instead of connection defined in `belongsTo()` model.

**Comment by topclaudy** [comment]
"Multiple connections" is a feature of Laravel, not Compoships. It's discussed here https://github.com/laravel/framework/issues/18545

**Comment by wojo1206** [comment]
@topclaudy Thanks for the info
