### ISSUE TITLE
whereHas seems not to work

### ISSUE THREAD

**Issue by ccarstens** [topclaudy/compoships#5]
Dear Claudin,

thank you for creating compoships!

Is it possible that the whereHas query does not work? 
When I try to query my model with whereHas and a compoship I get an Array to String conversion Exception. I use Laravel 5.5 and have both models extend compoships

Thank you for taking the time, compoships seems to make my life easier!
best
cornelius

    //Allocation and TrackingTask extend Awobaz\Compoships\Database\Eloquent\Model
    Allocation::whereHas('trackingTask');

results in:

<img width="895" alt="bildschirmfoto 2018-05-17 um 04 22 31" src="https://user-images.githubusercontent.com/29205799/40153422-13022c5a-598a-11e8-88f3-d564a8d91623.png">

**Comment by ccarstens** [comment]
hello @topclaudy 
thanks for getting back, I'm using the latest version and just tried to update compoships as mentioned by you in #3

**Comment by ccarstens** [comment]
Allocation:   

     use Awobaz\Compoships\Database\Eloquent\Model;
    use Carbon\Carbon;
    
    class Allocation extends Model
    {
        //...
        public function trackingTasks()
        {
            return $this->hasMany(
                TrackingTask::class,
                ['booking_id', 'vehicle_id'],
                ['booking_id', 'vehicle_id']
                );

        }
    }


TrackingTask:

    use Awobaz\Compoships\Database\Eloquent\Model;
    use Carbon\Carbon;
    use Illuminate\Database\Eloquent\SoftDeletes;
    
    class TrackingTask extends Model
    {
    
        use SoftDeletes;
        //...
        public function allocation()
        {
            return $this->belongsTo(Allocation::class,
                ['booking_id', 'vehicle_id'],
                ['booking_id', 'vehicle_id']);
        }
    }



I'm querying with 

    dump(Allocation::query()->has('trackingTasks')->get()->toArray());

**Comment by ccarstens** [comment]
hey @topclaudy 
it is `Awobaz\Compoships\Database\Eloquent\Builder`.

Is it expected behaviour, that the class `HasOneOrMany` from Laravel and not from Awobaz is being used?

<img width="706" alt="bildschirmfoto 2018-05-20 um 21 10 30" src="https://user-images.githubusercontent.com/29205799/40282678-38764390-5c73-11e8-8098-d9498cd3010c.png">

**Comment by topclaudy** [comment]
Hello @ccarstens 
I just added some unit tests. Checkout the master branch and run the tests (`phpunit`). I mocked the models (Allocation, TrackingTask) and all tests passed.

**Comment by topclaudy** [comment]
Please check the last version (1.0.4)
