### ISSUE TITLE
Parents

### ISSUE THREAD

**Issue by pMatt1988** [topclaudy/compoships#54]
I'm having trouble with a concept and I don't know if this is supported in Compoships.

Currently, I have a one to one relationship for mother and father, so

```
public function father() {
        return $this->hasOne(Person::class, 'id', 'father_id');
    }

    public function mother() {
        return $this->hasOne(Person::class, 'id', 'mother_id');
    }
```

And this works great, but for ease of traversing family trees, i'd like to add parents 

```
public function parents() {
        return $this->hasMany(Person::class, 'id', ['mother_id', 'father_id']);
    }
```

And also, to get children 

```
public function offspring() {
        return $this->hasMany(Person::class, ['mother_id', 'father_id'], 'id');
    }
```

I guess that Compoships isn't working as I'd expect in this situation and I was wondering if there is a way to get this to work or if it's a limitation in Compoships.

**Comment by topclaudy** [comment]
In Compoships, the size of the arrays has to be the same.
