### ISSUE TITLE
Problems Defining Special Relation

### ISSUE THREAD

**Issue by MannikJ** [topclaudy/compoships#58]
Hi,

I already tried to explain my problem in another package's issue, but it was not the right place either. I'm just going to link this issue and really hope anyone of you can help me out.

staudenmeir/belongs-to-through#37

I would also be open to add some custom tweaks to the relation, but I need to make it also work for eager loading.
 
I've tinkered a bit, but have not been successful so far. 
The following code is one example I came up with. The problem is there is binding of the current model's `service_jobs.id`. So how is that done anyways? If I would use `$this->id` from within the relation function I would lack the option of eager loading the relation, because the relation function would be called on a dummy model with empty attributes. Where does the binding come from on a normal `belongsTo` relation for example? What is done if this relation is eager-loaded? There are many questions, because I have not fully understood the whole concept of how the relation queries are constructed etc.

```php
public function customerService()
{
    return $this->belongsTo(
        CustomerService::class,
        ['customer_service.service_id', 'customer_service.customer_id'],
        ['service_jobs.service_id', 'jobs.customer_id']
    )
        ->select('customer_serice.*')
        ->join('jobs', function ($join) {
            return $join->on('jobs.id', '=', 'service_jobs.job_id');
        })
        ->join('service_jobs', function ($join) {
            return $join->on('service_jobs.id', '=', \DB::raw('?'));
        });
}
```

I would be really glad about any help

**Comment by topclaudy** [comment]
On way to solve this would be to implement Compoships support for `belongsToThrough`.
