### ISSUE TITLE
Does not support laravel 5.5?

### ISSUE THREAD

**Issue by jalllychun** [topclaudy/compoships#6]
I used this package to do a lazy eager loading and got this
```js
PHP Warning:  strtolower() expects parameter 1 to be string, array given in /vendor/laravel/framework/src/Illuminate/Database/Grammar.php on line 58
```

I simply used this trait and load a relation with two keys
```js
$this->belongsTo(A::class, ['key_1', 'key_2'], ['key_1', 'key_2']);
```

**Comment by topclaudy** [comment]
Compoships supports Laravel 5.5. Did you use the trait in both models as described in the documentation?

**Comment by ccgintranet** [comment]
We are also having this issue on 5.6

**Comment by topclaudy** [comment]
Please grab the last version and run the tests. If the problem persists, show me your integration.

Also make sure you follow this note from the documentation:

`
To define a multi-columns relationship from a model A to another model B, both models must either extend Awobaz\Compoships\Database\Eloquent\Model or use the Awobaz\Compoships\Compoships trait
`

**Comment by topclaudy** [comment]
Thanks for the feedback @ccgintranet. Really appreciated :)
