### ISSUE TITLE
updateOrCreate causes Illegal offset type

### ISSUE THREAD

**Issue by s1lviu** [topclaudy/compoships#63]
```
      UserGroupSettings::updateOrCreate(
                ['user_id' => $request->user()->id, 'fb_group_id' => $request->fb_group_id],
                ['interval' => $request->interval, 'active' => $request->active === 'on']
            );
```

```
class UserGroupSettings extends Model
{
    //use HasCompositePrimaryKey;
    use \Awobaz\Compoships\Compoships;

    public $timestamps = false;
    protected $primaryKey = ['user_id', 'fb_group_id'];
    public $incrementing = false;

```

When **the first param is set** `['user_id' => $request->user()->id, 'fb_group_id' => $request->fb_group_id],` on `updateOrCreate` , this warning appears and data is not saved
![image](https://user-images.githubusercontent.com/9863576/65022353-791fc800-d939-11e9-84b1-08b9f1a4d9ef.png)

**Comment by topclaudy** [comment]
This is not related to Compoships. You define your primary key as an array. As mentionned in the documentation, *Compoships doesn't bring support for composite keys in Laravel's Eloquent. This package only offers the ability to specify relationships based on more than one column*. If you need support for composite keys, you should probably re-enable the trait `HasCompositePrimaryKey` in your model.
