### ISSUE TITLE
Call newHasMany() newHasOne() newBelongsTo() when instantiating

### ISSUE THREAD

**Issue by mpyw** [topclaudy/compoships#64]
I'd like to use the following two library. Both of them have nice features.

- [staudenmeir/eloquent-eager-limit: Laravel Eloquent eager loading with limit](https://github.com/staudenmeir/eloquent-eager-limit)
- [topclaudy/compoships: Multi-columns relationships for Laravel's Eloquent ORM](https://github.com/topclaudy/compoships)

However, each `Builder` `Relation` is extended from Eloquent core. It's a little hard to go on with both of them.

Would you prefer to refactor them into Trait-based implementation?

Related: staudenmeir/eloquent-eager-limit#19

**Comment by mpyw** [comment]
I also think `hasMany` `hasOne` `belongsTo` should call `newHasMany` `newHasOne` `newBelongsTo`.

**Comment by mpyw** [comment]
[mpyw/compoships-eager-limit: topclaudy/compoships + staudenmeir/eloquent-eager-limit](https://github.com/mpyw/compoships-eager-limit)

[![Build Status](https://travis-ci.com/mpyw/compoships-eager-limit.svg?branch=master)](https://travis-ci.com/mpyw/compoships-eager-limit) [![Code Coverage](https://scrutinizer-ci.com/g/mpyw/compoships-eager-limit/badges/coverage.png?b=master)](https://scrutinizer-ci.com/g/mpyw/compoships-eager-limit/?branch=master) [![Scrutinizer Code Quality](https://scrutinizer-ci.com/g/mpyw/compoships-eager-limit/badges/quality-score.png?b=master)](https://scrutinizer-ci.com/g/mpyw/compoships-eager-limit/?branch=master)

**Comment by topclaudy** [comment]
May I know a little more about the errors/conflicts when you attempted to use both packages?

**Comment by mpyw** [comment]
@topclaudy I've just achieved to mixin them correctly 😆 

- Extend Compoships Query `Builder` and manully copy-and-paste EloquentEagerLimit implementation on it
- Extend Compoships `HasOne` `HasMany` Relation and mixin EloquentEagerLimit `HasLimit` trait 
- Extend EloquentEagerLimit Query `Grammar` to accept array partition

**Comment by mpyw** [comment]
Everything works fine, thanks! But 

> I also think `hasMany` `hasOne` `belongsTo` should call `newHasMany` `newHasOne` `newBelongsTo`.

I really think they should be correctly extended. I'll submit a PR later

**Comment by mpyw** [comment]
@staudenmeir Would you review my code and join as a collaborator? Thank you

**Comment by mpyw** [comment]
@topclaudy Would you review my code and join as a collaborator? Thank you
