### ISSUE TITLE
Optimise whereIn

### ISSUE THREAD

**Issue by SlyDave** [topclaudy/compoships#68]
This package is awesome, thanks.

A question, rather than chaining multiple and/or's could this be optimised to group the multi-column's into where In's ?

so rather than the output as is currently stands:

`select * from `mytable` where ((`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?) or (`mytable`.`another_id` = ? and `mytable`.`user_id` = ?)) and date(`starts_at`) <= ? and (`ends_at` is null or date(`ends_at`) >= ?) order by ends_at IS NULL DESC, ends_at DESC, created_at DESC`

So it's more like:

`select * from `mytable` where ((`mytable`.`another_id` IN (?) and `mytable`.`user_id` IN (?)) and date(`starts_at`) <= ? and (`ends_at` is null or date(`ends_at`) >= ?) order by ends_at IS NULL DESC, ends_at DESC, created_at DESC`

The size of the query gets pretty large once you start adding a lot of ids :)

**Comment by topclaudy** [comment]
The query is constructed based on the number of models when eager loading. It needs to add a condition for each IDs tuple from the collection of retrieved models. If it gets simplified, the eager loading would only match one model.

For simple relationships, a simple IN with the IDs is sufficient. For multi-columns relationships, it has to be constructed with multiple WHERE conditions.

**Comment by rezaulhreza** [comment]
You may acheive the following:
```php
$collection = collect([
            new ModelStub(['id' => 1, 'first_key' => 'abc', 'second_key' => 1]),
            new ModelStub(['id' => 2, 'first_key' => 'abc', 'second_key' => 2]),
            new ModelStub(['id' => 3, 'first_key' => 'def', 'second_key' => 1]),
        ]);

        $query = $builder->fromValues($collection, ['first_key', 'second_key']);

        $this->assertEquals(
            "select * from (values ('abc',1),('abc',2),('def',1)) as V(first_key,second_key)",
            $query->toSql()
        );
```
