### ISSUE TITLE
Error on User Model

### ISSUE THREAD

**Issue by ronssij** [topclaudy/compoships#71]
I am getting erros when I use the trais on User Model.

>  Symfony\Component\Debug\Exception\FatalErrorException  : Trait method newBaseQueryBuilder has not been applied, because there are collisions with other trait methods on App\Models\User

![image](https://user-images.githubusercontent.com/24932380/76834772-b3c2d880-6868-11ea-97d7-a174c2d5b1a1.png)
![image](https://user-images.githubusercontent.com/24932380/76834794-bc1b1380-6868-11ea-85dd-cd20e1883737.png)

**Comment by topclaudy** [comment]
There is a conflict between `Compoships` and `PaginationWithHavings`. Both redefine the method `newBaseQueryBuilder`.  You'll have to decide which one to keep.
