### ISSUE TITLE
I cannot understand the examples.

### ISSUE THREAD

**Issue by JunaidQadirB** [topclaudy/compoships#78]
Forgive my ignorance, I can't make sense of the examples given in the readme.
```php
 public function b()
    {
        return $this->hasMany('B', ['f1', 'f2'], ['l1', 'l2']);
    }
```

It would be great if real-life examples are used to convey the usage properly so that everyone can understand them easily.

Thanks,

**Comment by topclaudy** [comment]
Good point! I will update the doc in the upcoming days...

**Comment by topclaudy** [comment]
@JunaidQadirB Meanwhile, you may take a look at the examples from the tests https://github.com/topclaudy/compoships/blob/master/tests/ComposhipsTest.php

**Comment by JunaidQadirB** [comment]
Thanks. I'll check

**Comment by topclaudy** [comment]
The documentation has been updated to include a real-life scenario.
