### ISSUE TITLE
When I use whereHas, the sql's where condition is duplicated.

### ISSUE THREAD

**Issue by donshun** [topclaudy/compoships#8]
UserBinding Model

> public function user()
> {
>     return $this->hasOne('App\User', ['strName', 'strPwd'], ['strName', 'strPwd']);
> }

When I use whereHas

> $query->whereHas('user', function (Builder $query) use {
>     $query->where('user.iEnable', '=', 1);
> });

select count(*) as aggregate from `user_bindings` where (exists (select * from `user` where  

**`user_bindings`.`strName` = `user`.`strName` and `user_bindings`.`strPwd` = `user`.`strPwd` and `user`.`iEnable` = '1'** 

and 

**`user_bindings`.`strName` = `user`.`strName` and `user_bindings`.`strPwd` = `user`.`strPwd` and `user`.`iEnable` = '1'**)

Have any idea? Thank you very much.

**Comment by donshun** [comment]
Sorry, Can anyone help me@@?

**Comment by topclaudy** [comment]
Fixed in 1.0.6
