### ISSUE TITLE
Allow nullable columns

### ISSUE THREAD

**Issue by ChristopheB** [topclaudy/compoships#80]
I stumbled upon some unexpected results while working on a table where a column is nullable.
If I were to use the example in the tests folder, pretending vehicle_id could be null, we would have:

```php
$allocation = new Allocation();
$allocation->booking_id = 1;
$allocation->vehicle_id = null;
$allocation->save();

$allocation->trackingTasks()->save(new TrackingTask());
```

And the result is fairly unexpected:

```php
// EMPTY
$allocation->trackingTasks;
$allocation->trackingTasks()->get():
Allocation::first()->trackingTasks;

// OK, not empty
$allocation->load('trackingTasks')->trackingTasks;
Allocation::first()->load('trackingTasks')->trackingTasks;
Allocation::with('trackingTasks')->first()->trackingTasks;
```

After some investigations, it turns out that [this line is causing this issue](https://github.com/topclaudy/compoships/blob/e44d3abb6c84b5012c22d7eecc2d107f2f1204cd/src/Database/Eloquent/Relations/HasOneOrMany.php#L29).

```php
$this->query->whereNotNull($fullKey);
```

The reason of the presence of this line in the Laravel repository [is detailed here](https://github.com/laravel/framework/commit/1e80162e9a3a4c42a0079bd9f34e785197a66c07) ([PR here](https://github.com/laravel/framework/pull/8033), and an [interesting note here](https://github.com/laravel/ideas/issues/1341#issuecomment-622602397)).

I think it could be possible to drop this _whereNotNull_ condition when not all of the values are null, something like this:

```php
if (is_array($this->foreignKey)) {
    $allParentKeyValuesKeysAreNull = array_unique($parentKeyValue) === [null];

    foreach ($this->foreignKey as $index => $key) {
        list(, $key) = explode('.', $key);
        $fullKey = $this->getRelated()
                ->getTable().'.'.$key;
        $this->query->where($fullKey, '=', $parentKeyValue[$index]);

        if ($allParentKeyValuesKeysAreNull) {
            $this->query->whereNotNull($fullKey);
        }
    }
} 
```

I could make a PR for this if that new behaviour sounds good to you.

Thanks for your time, and thanks for Compoships.

**Comment by topclaudy** [comment]
@ChristopheB Thanks for the report. You can make a PR.
I think this will introduce some breaking behaviours in some integrations. I will bump the version to 2.0

**Comment by ChristopheB** [comment]
Just a side note on the presence of ```$this->query->whereNotNull($fullKey);```, as I struggled around it a bit: it is needed **only when a local auto incremented primary key is used in the relationship**.

In orders words, it ensures the **collection on a new instance without an id set** is the same as the **collection on the saved object with its definitive id**.
