### ISSUE TITLE
Is hasOneThrough compatible?

### ISSUE THREAD

**Issue by goda-kazuki** [topclaudy/compoships#84]
I want 
```
        return $this->hasOneThrough(KvsValue::class, BasicProperty::class,
            "property", ["key", "value"],
            "property", ["phone_shubetsu", "shubetsu"]);

```

But it doesn't work

Is there a solution?

**Comment by topclaudy** [comment]
@goda-kazuki No. hasOneThrough is not supported. 

List of supported relationships: 
https://github.com/topclaudy/compoships#supported-relationships

**Comment by JoeH20** [comment]
Is there plans to support hasOneThrough?
