### ISSUE TITLE
SQLSTATE[42703]: Undefined column

### ISSUE THREAD

**Issue by frankwrs** [topclaudy/compoships#85]
When I call the relation with two keys in an Eager way like `User::with('relation')->get` it's work very well. But when I call as a model propertie like `$user->relation` the query builder return error on query sintaxe. The laravel create a query with the table name instead of the attributes name like `select * from A where A.A = ? and A.A = ?`

**Comment by topclaudy** [comment]
Can you share you models schemas and the definition of the relationships?

**Comment by frankwrs** [comment]
Follows the models schemas and the definition of the relationships.

`class Item extends BaseModel
{
    use Compoships;
    protected $table = 'ctd.item';
    protected $primaryKey = 'item_id';

    public function relacaoAutor()
    {
        return $this->hasMany(RelacaoAutor::class, ['item_id','tipo_item_id'],['item_id','tipo_item_id']);
    }
}`

`class RelacaoAutor extends BaseModel
{
    use Compoships;

    protected $table = 'ctd.relacao_autor';
    protected $primaryKey = 'relacao_autor_id'; 
    protected $fillable = [
        'item_id',
        'autor_id',
        'tipo_item_id',
    ];
    public function item()
    {
        return $this->hasOne(Item::class, 'item_id', 'item_id');
    }
}`

When I try to access the relation by propertie `$item->relacaoAutor`  the resulting query is `select * from ctd.relacao_autor where ctd.relacao_autor.relacao_autor = ? and ctd.relacao_autor.relacao_autor = ?`

**Comment by frankwrs** [comment]
Follows the models schemas and the definition of the relationships.

`class Item extends BaseModel
{
use Compoships;
protected $table = 'ctd.item';
protected $primaryKey = 'item_id';
public function relacaoAutor()
{
    return $this->hasMany(RelacaoAutor::class, ['item_id','tipo_item_id'],['item_id','tipo_item_id']);
}
}`

`class RelacaoAutor extends BaseModel
{
use Compoships;
protected $table = 'ctd.relacao_autor';
protected $primaryKey = 'relacao_autor_id'; 
protected $fillable = [
    'item_id',
    'autor_id',
    'tipo_item_id',
];
public function item()
{
    return $this->hasOne(Item::class, 'item_id', 'item_id');
}
}`

When I try to access the relation by propertie $item->relacaoAutor the resulting query is select * from ctd.relacao_autor where ctd.relacao_autor.relacao_autor = ? and ctd.relacao_autor.relacao_autor = ?

**Comment by frankwrs** [comment]
Follows the models schemas and the definition of the relationships.

`class Item extends BaseModel { use Compoships; protected $table = 'ctd.item'; protected $primaryKey = 'item_id'; public function relacaoAutor() { return $this->hasMany(RelacaoAutor::class, ['item_id','tipo_item_id'],['item_id','tipo_item_id']); } }`

`class RelacaoAutor extends BaseModel { use Compoships; protected $table = 'ctd.relacao_autor'; protected $primaryKey = 'relacao_autor_id'; protected $fillable = [ 'item_id', 'autor_id', 'tipo_item_id', ]; public function item() { return $this->hasOne(Item::class, 'item_id', 'item_id'`); } }`

When I try to access the relation by propertie `$item->relacaoAutor` the resulting query is `select * from ctd.relacao_autor where ctd.relacao_autor.relacao_autor = ? and ctd.relacao_autor.relacao_autor = ?`

**Comment by topclaudy** [comment]
Fixed in 2.0.2
