### ISSUE TITLE
Does compoships support multiple columns using fieldnames and values?

### ISSUE THREAD

**Issue by qlj** [topclaudy/compoships#89]
I've briefly read the documentation, and you extend hasOne() or hasMany() by matching tables by their field-names.

I have a situation where one of my tables contains the fields:
* fk_id = a foreign-key to the pk of the parent table
* fk_table = a string value relating to the table containing the pk, i.e. 'customers' or 'suppliers'

Would compoships support something like:

$this->hasOne( 'App\Models\Address', [ 'fk_id', someusefulhelper('fk_table') ], ['id', 'customers'] );

?

**Comment by topclaudy** [comment]
For situation like this, I suggest the use of `where` clauses in the definition of the relationships.
