### ISSUE TITLE
supported Laravel 8?

### ISSUE THREAD

**Issue by hungcrush** [topclaudy/compoships#91]
I have an issue when upgrade to Laravel 8. Seems this package not supported Laravel 8 yet?

**Comment by isclopezm** [comment]
You made a PR to support Laravel 8, right? Why did you close it?

**Comment by hungcrush** [comment]
> You made a PR to support Laravel 8, right? Why did you close it?

I changed package name for my project so I closed the PR

https://packagist.org/packages/hungcrush/compoships

**Comment by topclaudy** [comment]
Check 2.0.3 for Laravel 8

**Comment by isclopezm** [comment]
Oh, I sent a PR a few minutes ago :-(

**Comment by topclaudy** [comment]
@isclopezm You sent the PR after 2.0.3. I'm gonna merge your PR

**Comment by topclaudy** [comment]
@isclopezm Merged! Thanks :)
