### ISSUE TITLE
Getting empty array in relations

### ISSUE THREAD

**Issue by Usama100** [topclaudy/compoships#96]
I am getting an empty array in a collection instance in relations.
My code is:

The User model

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Awobaz\Compoships\Compoships;
use App\Chat;

class User extends Authenticatable
{
    use Notifiable, HasSlug, Compoships;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        "last_online" => "datetime"
    ];

    public function chats()
    {
        return $this->hasMany(Chat::class, ['participant_1', 'participant_2'], ['participant_1', 'participant_2']);
    }
}

My Chat model code is:

use Illuminate\Database\Eloquent\Model;
use Awobaz\Compoships\Compoships;
use App\User;

class Chat extends Model
{
    use Compoships;
    
	protected $fillable = ["participant_1", "participant_2"];

    public function user()
    {
    	return $this->belongsTo(User::class, ['participant_1', 'participant_2'], ['participant_1', 'participant_2']);
    }
}

Please help me as I am not able to get the data.

**Comment by topclaudy** [comment]
Looks like you are trying to do something like https://github.com/topclaudy/compoships/issues/46 that Compoships doesn't support

**Comment by Usama100** [comment]
Yes, it was same as that. Thanks
