### ISSUE TITLE
Unable to apply the compoship relationship

### ISSUE THREAD

**Issue by bridgeyuwa** [topclaudy/compoships#97]
![Untitled (1)](https://user-images.githubusercontent.com/17090054/95137709-93a12b00-0760-11eb-8966-334a90c757b2.png)

I have three database tables which are in a One-To-Many relationship to a fourth table. 

They are joined by three conditions. How do I model this relationship  using Compoships?

The table **school_programs** has the 3 foreign key columns set as primary key because I need data for each combination of the three to be unique

Also, how would I be able to retrieve records and eager load with this type of database schema

Thanks

**Comment by topclaudy** [comment]
What relationships do you want to define?

**Comment by bridgeyuwa** [comment]
I want to define a **one to many** relationship where the table **school_programs** is made up of 3 composite keys from schools, degrees and programs

**Comment by topclaudy** [comment]
Relationship in the relational data model is defined from one table to another table (not multiple). Compoships doesn't change that. You can use Compoships to define a relationship from one table to only one table using multiple columns in the definition.

**Comment by bridgeyuwa** [comment]
So you are saying it is One is to One with both having the exact same data. eg 3 composite primary keys in A  then B has three foreign keys that reference to A. 
 All must match and it can't be just a one table Composite with foreign keys distributed among other tables like I have above???

**Comment by topclaudy** [comment]
No. It can't be just a one table with composite foreign keys distributed among other tables. Relationship are not defined like that in the relational data model. Relationships are one-way, but the link can be defined with multiple columns to/in the related table.

**Comment by bridgeyuwa** [comment]
If that is the case what would you recommend I do? cause if I use query builder, maintenance might turn out to be a nightmare later on.

**Comment by topclaudy** [comment]
It depends on what you're trying to accomplish. You can still use the default Laravel relationships though, to define separate relationship. For example:

- A degree relationship from `school_programs` to `degrees`, using degree_id and the id column from the `degrees` table. Or the inverse:
- A schoolPrograms relationship from `degrees` to `school_programs`, using id and the degree_id column from the `school_programs` table

....

**Comment by bridgeyuwa** [comment]
Thanks alot for the support
